version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.2.0

jobs:
  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - command: echo "Helllo World"

workflows:
  test:
    jobs:
      - test
